ccflags-y := -O3 -funsafe-math-optimizations -fgcse-lm -fgcse-sm -fsched-spec-load -fforce-addr -fsingle-precision-constant -mcpu=cortex-a7 -mtune=cortex-a7 -mfpu=neon
obj-y += msm_ion.o ion_cp_common.o ion_iommu_map.o
